colors:
- [59, 187, 230]
names: [tom]
nc: 1
train: /content/drive/MyDrive/AI/optimlabel/dataset/dautommin/box2/images/train
val:  /content/drive/MyDrive/AI/optimlabel/dataset/dautommin/box2/images/val
